-- create table if not exists titles (
-- 	id int unsigned auto_increment primary key,
-- 	FormalTitle_jp varchar(255),
-- 	HiraganaTitle varchar(255),
-- 	KatakanaTitle varchar(255),
-- 	ShortTitle varchar(255),
-- 	FormalTitle_eg varchar(255),
-- 	CapitalTitle varchar(255),
-- 	SmallTitle varchar(255),
--     imageurl varchar(2000),
--     quote varchar(255),
--     quoteurl varchar(2000),
-- 	created datetime default now(),
-- 	modified datetime default now()
-- );

-- create table requesttitles (
-- 	id int unsigned auto_increment primary key,
-- 	RequestTitle varchar(255)
-- );


insert into titles (FormalTitle_jp, HiraganaTitle, KatakanaTitle, ShortTitle, FormalTitle_eg, CapitalTitle, SmallTitle, imageurl, quote, quoteurl) values 
('やはり俺の青春ラブコメはまちがっている。', 'やはりおれのせいしゅんらぶこめはまちがっている。', 'ヤハリオレノセイシュンラブコメハマチガッテイル。', '俺ガイル', 'My Youth Romantic Comedy Is Wrong as I Expected', 'MY YOUTH ROMANTIC COMEDY IS WRONG AS I EXPECTED', 'my youth romantic comedy is wrong as i expected', 'https://notsu08.com/wp-content/uploads/2019/03/D2CFL72WsAANu84.jpg', 'ノツのスローライフ計画', 'https://notsu08.com/oregairu-anime-3ki/' ),
('ワンパンマン', 'わんぱんまん', '', '', 'One Punch Man', 'ONE PUNCH MAN', 'one punch man', 'https://pics.prcm.jp/90ce610d0fd1f/82267146/jpeg/82267146.jpeg', 'GMO', 'https://prcm.jp/album/90ce610d0fd1f/pic/82267146?keyword=%E3%83%AF%E3%83%B3%E3%83%91%E3%83%B3%E3%83%9E%E3%83%B3&page=1' ),
('鬼滅の刃', 'きめつのやいば', 'キメツノヤイバ', '', 'Demon Slayer', 'DEMON SLAYER', 'demon slayer', 'https://www.shonenjump.com/j/img/_news/190218kimetsu_1.jpg', '少年ジャンプ公式サイト', 'https://www.shonenjump.com/j/2019/02/18/190218_kimetsu001.html' ),
('ダンジョンに出会いを求めるのは間違っているだろうか', 'だんじょんにであいをもとめるのはまちがっているだろうか', 'ダンジョンニデアイヲモトメルノハマチガッテイルダロウカ', 'ダンまち', 'Is It Wrong to Try to Pick Up Girls in a Dungeon?', 'IS IT WRONG TO TRY TO PICK UP GIRLS IN A DUNGEON?', 'is it wrong to try to pick up girls in a dungeon?', 'https://akiba-souken.k-img.com/assets/images/article/000/818/t640_818098.jpg', 'アキバ総研', 'https://akiba-souken.com/article/40414/' ),
('進撃の巨人', 'しんげきのきょじん', 'シンゲキノキョジン', '', 'Attack on Titan', 'ATTACK ON TITAN', 'attack on titan', 'https://images-na.ssl-images-amazon.com/images/I/81ly5qLKROL._SL1350_.jpg', 'TVアニメ「進撃の巨人」Season 2', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E9%80%B2%E6%92%83%E3%81%AE%E5%B7%A8%E4%BA%BA%E3%80%8DSeason-2-Vol-1-Blu-ray-%E6%A2%B6%E8%A3%95%E8%B2%B4/dp/B06XT226DZ'),
('ボボボーボ・ボーボボ', 'ぼぼぼーぼ・ぼーぼぼ', '', '', 'Bobobo-bo Bo-bobo', 'BOBOBO-BO BO-BOBO', 'bobobo-bo bo-bobo', 'https://blog-imgs-80.fc2.com/m/a/n/mangakikou/1438586706449.jpg', 'マンガ中毒', 'https://www.mangajunky.net/blog-entry-6365.html'),
('名探偵コナン', 'めいたんていこなん', 'メイタンテイコナン', 'コナン', 'Case Closed', 'CASE CLOSED', 'case closed', 'https://www.conan-movie.jp/img/home2/conan.png', '劇場版名探偵コナン『紺青の拳』', 'https://www.conan-movie.jp/'),
('落第騎士の英雄譚', 'らくだいきしのきゃばるりぃ', 'ラクダイキシノキャバルリィ', '', 'Chivalry of a Failed Knight', 'CHIVALRY OF A FAILED KNIGHT', 'chivalry of a failed knight', 'https://hayabusa.io/abema/programs/174-5_s0_p1/thumb001.q85.w640.h360.q85.x2.v1489740320.webp', 'AbemaTV落第騎士の英雄譚', 'https://abema.tv/channels/midnight-anime/slots/9haApNaqLcXdS7' ),
('青の祓魔師', 'あおのえくそしすと', 'アオノエクソシスト', '青エク', 'Blue Exorcist', 'BLUE EXORCIST', 'blue exorcist', 'https://akiba-souken.k-img.com/assets/images/official/24/2457f3847fcecff92df07209981a72c0.jpg', 'アキバ総研', 'https://akiba-souken.com/anime/4498/'),
('アイドル事変', 'あいどるじへん', 'アイドルジヘン', '', 'Idol Incidents', 'IDOL INCIDENTS', 'idol incidents', 'https://img.animatetimes.com/news/visual/2016/1471483676_1_1_0957fbd60a5b7254a25b252268a5d8f5.jpg', 'animate Times', 'https://www.animatetimes.com/news/details.php?id=1471483676'),
('蒼の彼方のフォーリズム', 'あおのかなたのふぉーりずむ', 'アオノカナタノフォ＝リズム', 'あおかな', 'Four Rhythm Across the Blue', 'FOUR RHYTHM ACROSS THE BLUE', 'four rhythm across the blue', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS6yX8nOeqsaIxAhxHB5Bb6v54PR3RruuszxdHaVGecqQjmHF03', '「蒼の彼方のフォーリズム」公式サイト', 'https://aokana-anime.com/'),
('青春×機関銃', 'あおはるきかんじゅう', 'アオハルキカンジュウ', '', 'AOHARU×MACHINEGUN', 'AOHARU×MACHINEGUN', 'aoharu×machinegun', 'https://images-na.ssl-images-amazon.com/images/I/51tN7eQCyBL.jpg', 'アキバ総研', 'https://akiba-souken.com/anime/18773/'),
('赤髪の白雪姫', 'あかがみのしらゆきひめ', 'アカガミノシラユキヒメ', '', 'Snow White with the Red Hair', 'SNOW WHITE WITH THE RED HAIR', 'snow white with the red hair', 'https://tshop.r10s.jp/book/cabinet/5763/9784592105763.jpg?fitin=200:300&composite-to=*,*|200:300', '楽天ブックス', 'https://books.rakuten.co.jp/rb/14771814/'),
('赤毛のアン', 'あかげのあん', 'アカゲノアン', '', 'Anne of Green Gables', 'ANNE OF GREEN GABLES', 'anne of green gables', 'https://images-na.ssl-images-amazon.com/images/I/41EJCFVTEGL.jpg', 'Amazon.com', 'https://www.amazon.co.jp/%E8%B5%A4%E6%AF%9B%E3%81%AE%E3%82%A2%E3%83%B3-TV%E3%82%B5%E3%83%B3%E3%83%88%E3%83%A9/dp/B00005EN7Y'),
('暁のヨナ', 'あかつきのよな', 'アカツキノヨナ', '', 'YONA -The girl standing in the blush of dawn-', 'YONA -THE GIRL STANDING IN THE BLUSH OF DAWN-', 'yona -the girl standing in the blush of dawn-', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSH0zk1bLwxk6f3zJcJt8KbyGSfLy7dYU_rdNr8OzHAzddNzCvP', 'animate Times', 'https://www.animatetimes.com/news/details.php?id=1427332262'),
('茜色に染まる坂', 'あかねいろにそまるさか', 'アカネイロニソマルサカ', '', 'Akaneiro ni Somaru Saka', 'AKANEIRO NI SOMARU SAKA', 'akaneiro ni somaru saka', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQJbDr2TLXYNqnlBZGpo0rdSG8NqLOU-KtrKdLc1a6ZQFbvVSOS', 'Amazon.com', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%81%82%E3%81%8B%E3%81%AD%E8%89%B2%E3%81%AB%E6%9F%93%E3%81%BE%E3%82%8B%E5%9D%82%E3%80%8D%E3%83%89%E3%83%A9%E3%83%9ECD-%E3%83%89%E3%83%A9%E3%83%9E/dp/B001LWJZ5W'),
('アカメが斬る!', 'あかめがきる', 'アカメガキル', '', 'Akame ga Kill!', 'AKAME GA KILL!', 'akame ga kill!', 'https://sinsteal.com/wp-content/uploads/2018/06/%E3%82%A2%E3%82%AB%E3%83%A1%E3%81%8C%E6%96%AC%E3%82%8B%EF%BC%81.jpg', '© タカヒロ・田代哲也／スクウェアエニックス「アカメが斬る！」製作委員会', ''),
('惡の華', 'あくのはな', 'アクノハナ', '', 'Flowers of Evil', 'FLOWERS OF EVIL', 'flowers of evil', 'https://akiba-souken.k-img.com/thumbnail/images/official/5b/5b67a5fc6e0116288e5d31a22a883cfa.jpg?w=200&h=200', 'アキバ総研', 'https://akiba-souken.com/anime/11499/'),
('悪魔のドリル', 'あくまのどりる', 'アクマノドリル', '', 'Riddle Story of Devil', 'RIDDLE STORY OF DEVIL', 'riddle story of devil', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRNU2uE3PdOWa_8NC0gJDPAac5U6xordq1COiJNxz0WeSFzmoia', 'アニメ「悪魔のドリル」公式サイト', 'http://akuma-riddle.com/'),
('あさがおと加瀬さん。', 'あさがおとかせさん', '', '', 'Asagao to Kase-san', '', '', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS6B5MTa1cI-Upi5Hb_idBr0sf6SHjUPrZYN0a8dUrK02heK0Kd', 'Amazon | 明日への扉', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.co.jp%2F%25E6%2598%258E%25E6%2597%25A5%25E3%2581%25B8%25E3%2581%25AE%25E6%2589%2589-%25E3%2580%258C%25E3%2581%2582%25E3%2581%2595%25E3%2581%258C%25E3%2581%258A%25E3%2581%25A8%25E5%258A%25A0%25E7%2580%25AC%25E3%2581%2595%25E3%2582%2593%25E3%2580%2582%25E3%2580%258D%25E4%25B8%25BB%25E9%25A1%258C%25E6%25AD%258C-%25E5%25B1%25B1%25E7%2594%25B0%25E7%25B5%2590%25E8%25A1%25A3-%25E9%25AB%2598%25E6%25A9%258B%25E6%259C%25AA%25E5%25A5%2588%25E7%25BE%258E-%25E5%258A%25A0%25E7%2580%25AC%25E5%258F%258B%25E9%25A6%2599%2Fdp%2FB07CCFSCSD&psig=AOvVaw0YUKbjak8LgH-a3Zqhbtc0&ust=1571550329066000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCOiM7KrPp-UCFQAAAAAdAAAAABAE'),
('あしたのジョー', 'あしたのじょー', 'アシタノジョー', '', "Tomorrow's Joe", "TOMORROW'S JOE", "tomorrow's joe", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT75gTLeFECbQkA57kn18iXrtuaNAnfcIDF6Q8IAfPM-JgyY1Dy', 'Amazon あしたのジョー サントラ', 'https://www.amazon.co.jp/%E3%81%82%E3%81%97%E3%81%9F%E3%81%AE%E3%82%B8%E3%83%A7%E3%83%BC-%E3%82%B5%E3%83%B3%E3%83%88%E3%83%A9/dp/B00005GFMX'),
('あずまんが大王', 'あずまんがだいおう', 'アズマンガダイオウ', '', 'Azumanga Daioh', 'AZUMANGA DAIOH', 'azumanga daioh', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQO3vtPwI3QbGMcSEZGNe-3csiGyMYNyYEu-6Oi-aK5t6uoUoAs', 'あずまんが大王　GENCO', 'https://www.genco.co.jp/works/1979/'),
('あそびあそばせ', 'あそびあそばせ', 'アソビアソバセ', '', 'Asobi Asobase', 'ASOBI ASOBASE', 'asobi asobase', 'https://hayabusa.io/abema/programs/25-98_s1_p1/thumb001.q85.w640.h360.q85.x2.v1541493031.webp', 'Abema.tv', 'https://abema.tv/channels/anime-live/slots/EBDGy3dDPeuDAP'),
('あたしンち', 'あたしんち', 'アタシンチ', '', "Atashin'chi", "ATASHIN'CHI", "atashin'chi", 'https://keraeiko.com/wp-content/uploads/2019/03/d4158370ad337ba762fe54647c727b48-1.jpg', 'けらえいこ公式サイト', 'https://keraeiko.com/'),
('あっくんとカノジョ', 'あっくんとかのじょ', 'アックントカノジョ', '', 'Akkun to Kanojo', 'AKKUN TO KANOJO', 'akkun to kanojo', 'https://lohas.nicoseiga.jp/material/d8a852/7657130', 'ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_MF03000018010000_68/'),
('あっちこっち', 'あっちこっち', 'アッチコッチ', '', 'PLACE TO PLACE', 'PLACE TO PLACE', 'place to place', 'https://images-na.ssl-images-amazon.com/images/I/81OQpIyKXEL._SX679_.jpg', 'Amazon.com', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%81%82%E3%81%A3%E3%81%A1%E3%81%93%E3%81%A3%E3%81%A1%E3%80%8D%E3%82%AA%E3%83%BC%E3%83%97%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%86%E3%83%BC%E3%83%9E-%E3%81%82%E3%81%A3%E3%81%A1%E3%81%A7%E3%81%93%E3%81%A3%E3%81%A1%E3%81%A7-%E3%81%82%E3%81%A3%E3%81%A1%E2%87%94%E3%81%93%E3%81%A3%E3%81%A1/dp/B007EDNJYK'),
('兄に付ける薬はない！', 'あににつけるくすりはない', 'アニニツケルクスリハナイ', '', 'Ani ni Tsukeru Kusuri wa Nai!', 'ANI NI TSUKERU KUSURI WA NAI!', 'ani ni tsukeru kusuri wa nai!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTWO-mFhGdYNAh_xuue84RHarpLxD43QCziQzCo20Dsj7KKRnmQ', 'Amazon.co.jp', 'https://www.amazon.co.jp/%E5%85%84%E3%81%AB%E4%BB%98%E3%81%91%E3%82%8B%E8%96%AC%E3%81%AF%E3%81%AA%E3%81%84%EF%BC%81-%E5%BF%AB%E6%8A%8A%E6%88%91%E5%93%A5%E5%B8%AF%E8%B5%B0-%E3%82%B7%E3%83%BC%E3%82%BA%E3%83%B31/dp/B07F27YLCN'),
('アニメで分かる心療内科', 'あにめでわかるしんりょうないか', 'アニメデワカルシンリョウナイカ', '', 'Anime de Wakaru Shinryounaika', 'ANIME DE WAKARU SHINRYOUNAIKA', 'anime de wakaru shinryounaika', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSzDHdvZgoejxElok9uly347ypZoXSEspqDLFts21_PCp17A9qN', '「アニメで分かる心療内科」公式サイト', 'http://mental-anime.jp/'),
('あの夏で待ってる', 'あのなつでまってる', 'アノナツデマッテル', '', 'Waiting in the Summer', 'WAITING IN THE SUMMER', 'waiting in the summer', 'https://images-na.ssl-images-amazon.com/images/I/810sF9pTUCL._SL1500_.jpg', 'Amazon.co.jp', 'https://www.amazon.co.jp/%E3%81%82%E3%81%AE%E5%A4%8F%E3%81%A7%E5%BE%85%E3%81%A3%E3%81%A6%E3%82%8B-Blu-ray-Complete-%E5%88%9D%E5%9B%9E%E9%99%90%E5%AE%9A%E7%94%9F%E7%94%A3-%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E5%84%AA%E5%85%88%E8%B2%A9%E5%A3%B2%E7%94%B3%E8%BE%BC%E5%88%B8%E4%BB%98%E3%81%8D/dp/B00KXKX20M'),
('あの日見た花の名前を僕たちはまだ知らない。', 'あのひみたはなのなまえをぼくたちはまだしらない', 'アノヒミタハナノナマエヲボクタチハマダシラナイ', 'あのはな', 'Anohana: The Flower We Saw That Day', 'ANOHANA: THE FLOWER WE SAW THAT DAY', 'anohana: the flower we saw that day', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTJW02K2TEpvAK-HDjYfzHAmruQz-43vSMRjzoNEFBaM833qiiz', 'あのはな 公式サイト', 'https://www.anohana.jp/tv/'),
('あひるの空', 'あひるのそら', 'アヒルノソラ', '', 'Ahiru no Sora', 'AHIRU NO SORA', 'ahiru no sora', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTDjE50hc20MUBg1-7QqmZ4rRe7xa6idPkVVDDsKA4unNuMwl2B', 'AnimeAnime.jp', 'https://animeanime.jp/article/2019/05/08/45324.html'),
('アホガール', 'あほがーる', 'アホガール', '', 'Aho-Girl', 'AHO-GIRL', 'aho-girl', 'http://ahogirl.jp/img/chara_thum_1.png', 'アホガール 公式サイト', 'http://ahogirl.jp/'),
('甘々と稲妻', 'あまあまといなずま', 'アマアマトイナズマ', '', 'Sweetness and Lightning', 'SWEETNESS AND LIGHTNING', 'sweetness and lightning', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRcZMWjunynaLMiBVk39jZE6HDV055a0ipB7spfc-cQJI0GFH_3', 'Amazon.co.jp', 'https://www.amazon.co.jp/%E7%94%98%E3%80%85%E3%81%A8%E7%A8%B2%E5%A6%BB-Blu-ray-BOX-%E4%B8%AD%E6%9D%91%E6%82%A0%E4%B8%80/dp/B01HTH2Z7C'),
('アマガミSS', 'あまがみSS', '', '', 'Amagami SS ', 'AMAGAMI', 'amagami', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTwJUKPMp5v0ryUiEcD-QAgC_9lpjUiTBkiwefAkObMK7dhooVa', 'Amazon.co.jp|オープニングテーマ', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%82%A2%E3%83%9E%E3%82%AC%E3%83%9FSS%E3%80%8D%E3%82%AA%E3%83%BC%E3%83%97%E3%83%8B%E3%83%B3%E3%82%B0%E3%83%86%E3%83%BC%E3%83%9E-i-Love-azusa/dp/B003L6L824'),
('雨色ココア', 'あめいろここあ', 'アメイロココア', '', 'Rainy Cocoa', 'RAINY COCOA', 'rainy cocoa', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcShVNYCSgRG9M1j4jDkdWeOMW6HvmsSn5Pz_9Ll2BCCw55IcAU-', '雨色ココア', 'http://rainycocoa.jp/index.html'),
('荒ぶる季節の乙女どもよ。', 'あらぶるきせつのおとめどもよ', 'アラブルキセツノアトメドモヨ', '', 'O Maidens in Your Savage Season', 'O MAIDENS IN YOUR SAVAGE SEASON', 'o maidens in your savage season', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTosi9lV6LszyRxMdbV_IGj4QdpynQ28hNlWmnkNt92EzgecSV8', '公式Twitter', 'https://twitter.com/araotoproject'),
('ありふれた職業で世界最強', 'ありふれたしょくぎょうでせかいさいきょう', 'アリフレタセカイデセカイサイキョウ', '', "Arifureta: From Commonplace to World's Strongest", "ARIFURETA: FROM COMMONPLACE TO WORLD'S STRONGEST", "arifureta: from commonplace to world's strongest", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTIn7K05mASRwMzSTNaXurxl7EP9qJktkWrQMfB7gLVAbfhmYdl', 'AnimeAnime.jp', 'https://animeanime.jp/article/2018/12/29/42430.html'),
('アルスラーン戦記', 'あるすらーんせんき', 'アルスラーンセンキ', '', 'The Heroic Legend of Arslan', 'THE HEROIC LEGEND OF ARSLAN', 'the heroic legend of arslan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQtoMPJq39YryYJ0Mmot3SKersu5G3NpYwUDvl1StZJfilC1v0Z', 'アルスラーン戦記 番組サイト', 'https://www.mbs.jp/arslan/'),
('あるゾンビ少女の災難', 'あるぞんびしょうじょのさいなん', 'アルゾンビショウジョノサイナン', '', 'Calamity of a Zombie Girl', 'CALAMITY OF A ZOMBIE GIRL', 'calamity of a zombie girl', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRXWJPZ3c0rQqPCLKwMzaGFGuSFbrnshq72JHZIqQ5wz88ksL04', 'anime Times', 'https://www.animatetimes.com/news/details.php?id=1530588023'),
('暗殺教室', 'あんさつきょうしつ', 'アンサツキョウシツ', '', 'Assassination Classroom', 'ASSASSINATION CLASSROOM', 'assassination classroom', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ8foeU_olM9Ub1ccYRK_uxWd3Q36D-Npb1MqO0aPC7vDQpxD-8', 'TVアニメ 公式サイト', 'https://www.ansatsu-anime.com/'),
('RD洗脳調査室', 'あーるでぃーせんのうちょうさすつ', 'アールディーセンノウチョウサスツ', '', 'Real Drive', 'REAL DRIVE', 'real drive', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRpBCQlB7VKVOthU_chY_07ryJwLRAPbkUzWJWm9ApP4Nl8Mms_', '半神半技 レビュー', 'https://kamiwaza-half.com/2017/04/02/rd-%E6%BD%9C%E8%84%B3%E8%AA%BF%E6%9F%BB%E5%AE%A4/'),
('異世界かるてっと', 'いせかいかるてっと', 'イセカイカルテット', 'いせかる', 'Isekai Quartet', 'ISEKAI QUARTET', 'isekai quartet', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQorjSA13V0A6GwAIraAK0XlN_vKtdeyG65I_1jHrT5eUY_gTwv', '公式Twitter', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Fisekai_quartet&psig=AOvVaw0mbV1FjwBxWukN0fC431lv&ust=1571552009406000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLjTkczVp-UCFQAAAAAdAAAAABAE'),
('異世界食堂', 'いせかいしょくどう', 'イセカイショクドウ', '', 'Restaurant to Another World', 'RESTAURANT TO ANOTHER WORLD', 'restaurant to another world', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQWiB4l_BYxV0PSt7SNSu19BWzDoRH4FyBmBH7E7kJiaqERu7xi', '公式Twitter', 'https://www.google.com/url?sa=i&url=https%3A%2F%2Ftwitter.com%2Fnekoya_pr&psig=AOvVaw1r_AflD065BJbJdd1xXZCR&ust=1571552090490000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIj85_LVp-UCFQAAAAAdAAAAABAE'),
('異世界チート魔術師', 'いせかいちーとまじしゃん', 'イセカイチートマジシャン', '異世界チート', 'Isekai Cheat Magician', 'ISEKAI CHEAT MAGICIAN', 'isekai cheat magician', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS8z6ch5S9IpK_X7R5ZnfPUxsrxgnXndxEoVw5F42HooX2qX0hU', 'ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_KS01000054010000_68/'),
('異世界の聖機師物語', 'いせかいのせいきしものがたり', 'イセカイセイキシモノガタリ', '', 'Tenchi Muyo! War on Geminar', 'TENCHI MUYO! WAR ON GEMINAR', 'tenchi muyo! war on geminar', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRm6iMpf5njUe3pJxv2WsbuK-2RLIyW_PlQle1f7qSR3NweElO3', 'Amazon.co.jp', 'https://www.amazon.co.jp/%E7%95%B0%E4%B8%96%E7%95%8C%E3%81%AE%E8%81%96%E6%A9%9F%E5%B8%AB%E7%89%A9%E8%AA%9E-5-DVD-%E4%B8%8B%E9%87%8E%E7%B4%98/dp/B002HP60XC'),
('異世界はスマートフォンとともに。', 'いせかいはすまーとふぉんとともに', 'イセカイハスマートフォントトモニ', '', 'In Another World with My Smartphone', 'IN ANOTHER WORLD WITH MY SMARTPHONE', 'in another world with my smartphone', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTO8KDuOTuUyCb_wfTIH3u2BjNxHQKQl63DAxNCfEZyLHV2oL8B', 'Amazon.co.jp', 'https://www.amazon.co.jp/%EF%BC%B4%EF%BC%B6%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E7%95%B0%E4%B8%96%E7%95%8C%E3%81%AF%E3%82%B9%E3%83%9E%E3%83%BC%E3%83%88%E3%83%95%E3%82%A9%E3%83%B3%E3%81%A8%E3%81%A8%E3%82%82%E3%81%AB%E3%80%82%E3%80%8D%EF%BD%96%EF%BD%8F%EF%BD%8C%EF%BC%8E%EF%BC%91%E3%80%90%EF%BC%A4%EF%BC%B6%EF%BC%A4%E3%80%91-DVD-%E5%86%AC%E5%8E%9F%E3%83%91%E3%83%88%E3%83%A9/dp/B073VYS9N4'),
('いつだって僕らの恋は10センチだった。', 'いつだってぼくらのこいは10せんちだった', 'イツダッテボクラノコイハ10センチダッタ', '', 'We have always been 10 cm space', 'WE HAVE ALWAYS BEEN 10 CM SPACE', 'we have always been 10 cm space', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSVqtuO4cV9z7DI9mkmgyE0yidiVPho6SPDv1jAJYovg_HIiSWM', 'いつだって僕らの恋は10センチだった。', 'https://www.honeyworks-movie.jp/'),
('いぬやしき', '', 'イヌヤシキ', '', 'Inuyashiki', 'INUYASHIKI', 'inuyashiki', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTrvZWl1NnwAUZn0Lq2-4JzyNnJ9vBD-PAYFpjnwswE7EtmqwLn', 'amazon.co.jp', 'https://www.amazon.co.jp/%E3%81%84%E3%81%AC%E3%82%84%E3%81%97%E3%81%8D%EF%BC%88%EF%BC%91%EF%BC%89-%E3%82%A4%E3%83%96%E3%83%8B%E3%83%B3%E3%82%B0%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9-%E5%A5%A5%E6%B5%A9%E5%93%89-ebook/dp/B00KCL6Y2U'),
('異能バトルは日常系のなかで', 'いのうばとるはにちじょうけいのなかで', 'イノウバトルハニチジョウケイノナカデ', '', 'When Supernatural Battles Became Commomplace', 'WHEN SUPERNATURAL BATTLES BECAME COMMOMPLACE', 'when supernatural battles became commomplace', 'https://images-na.ssl-images-amazon.com/images/I/61b7qGOz3AL._SX411_BO1,204,203,200_.jpg', 'amazon.co.jp', 'https://www.amazon.co.jp/%E7%95%B0%E8%83%BD%E3%83%90%E3%83%88%E3%83%AB%E3%81%AF%E6%97%A5%E5%B8%B8%E7%B3%BB%E3%81%AE%E3%81%AA%E3%81%8B%E3%81%A7-10-%E3%83%89%E3%83%A9%E3%83%9ECD%E4%BB%98%E3%81%8D%E9%99%90%E5%AE%9A%E7%89%B9%E8%A3%85%E7%89%88-GA%E6%96%87%E5%BA%AB-%E5%85%AC%E5%A4%AA/dp/4797382376'),
('宇宙兄弟', 'うちゅうきょうだい', 'ウチュウキョウダイ', '', 'Space Brothers', 'SPACE BROTHERS', 'space brothers', 'https://images-fe.ssl-images-amazon.com/images/I/51e7yjkjRwL.jpg', 'amazon.co.jp 宇宙兄弟コミック', 'https://www.amazon.co.jp/dp/B009KWUGMQ/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1'),
('有頂天家族', 'うちょうてんかぞく', 'ウチョウテンカゾク', '', 'The Eccentric Family', 'THE ECCENTRIC FAMILY', 'the eccentric family', 'https://www.lantis.jp/img/tmp2_423be96e7d7aab6bbb80f47be46eb599.jpg', '有頂天家族 | Lantis web site', 'https://www.lantis.jp/title/uchoten-anime/disco_7e3912096ddd01a6635fe0063eb43da0.html'),
('うどんの国の金色毛鞠', 'うどんのくにのきにろけまり', 'ウドンノクニノキンイロケマリ', '', "Poco's Udon World", "POCO'S UDON WORLD", "poco's udon world", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRjq182t-1gW8foEx4R5CkplfL_cjCQb7nFPteyWod3EvL25dDY', 'うどんの国の金色毛鞠 | くらげバンチ', 'https://kuragebunch.com/episode/10834108156629662531'),
('うらら迷路帖', 'うららめいろちょう', 'ウララメイロチョウ', '', 'Urara Meirocho', 'URARA MEIROCHO', 'urara meirocho', 'https://www.tbs.co.jp/anime/urara/img/webtop.png', 'うらら迷路帖 公式ホームページ', 'https://www.tbs.co.jp/anime/urara/'),
('エリアの騎士', 'えりあのきし', 'エリアノキシ', '', 'THE KNIGHT in THE AREA', 'THE KNIGHT IN THE AREA', 'the knight in the area', 'https://img.anime-hiroba.com/area-no-kishi.jpg', 'エリアの騎士 アニメ広場', 'https://www.anime-hiroba.com/anime/area-no-kishi/'),
('エロマンガ先生', '', '', '', 'Eromanga Sensei', '', '', 'https://eromanga-sensei.com/assets/img/top/kv.jpg', 'エロマンガ先生 アニメ公式サイト', 'https://eromanga-sensei.com/'),
('炎炎ノ消防隊', 'えんえんのしょうぼうたい', 'エンエンノショウボウタイ', '', 'Fire Force', 'FIRE FORCE', 'fire force', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQCNT4Om1CoZA9eEaF9wjxL8S4cp00cXNyQbKLMVBN6cLQy5uNy', '炎炎ノ消防隊 | MBS', 'https://www.mbs.jp/fireforce/'),
('オオカミ少女と黒王子', 'おおかみしょうじょとくろおうじ', 'オオカミショウジョトクロオウジ', '', 'Wolf Girl and Black Prince', 'WOLF GIRL AND BLACK PRINCE', 'wolf girl and black prince', 'http://ototoy.jp/news/image.php/80566/0.jpg', 'ガジェット通信 GetNews', 'https://getnews.jp/archives/704904'),
('おおきく振りかぶって', 'おおきくふりかぶって', 'オオキクフリカブッテ', 'おおふり', 'Big Windup!', 'BIG WINDUP', 'big windup', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSs9G2F_sSsjSBhAAnPVCPLy4ht9K0PXvA5E5YE_gBSEJtz2cVM', 'COMPLETE Blu-ray Disc BOX', 'https://www.oofuri.com/'),
('おくさまが生徒会長!', 'おくさまがせいとかいちょう', 'オクサマガセイトカイチョウ', '', 'My Wife is the Student Council President', 'MY WIFE IS THE STUDENT COUNCIL PRESIDENT', 'my wife is the student council president', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRdpibtEjMqTBv6sInrvEoODTVxmwdcJvKLRzYy1OUOjARDtdSP', 'amazon.co.jp', 'https://www.amazon.co.jp/%E3%82%AD%E3%83%A9%E3%82%AD%E3%83%A9%E2%98%86%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%97%E3%83%AD%E3%83%BC%E3%83%A9%E3%83%BC-%E6%81%8B%E3%81%AB%E3%81%BE%E3%81%A4%E3%82%8F%E3%82%8B%E3%82%A8%E3%83%88%E3%82%BB%E3%83%88%E3%83%A9-%E3%81%8A%E3%81%8F%E3%81%95%E3%81%BE%E3%81%8C%E7%94%9F%E5%BE%92%E4%BC%9A%E9%95%B7-%E3%83%9F%E3%83%8B%E3%82%A2%E3%83%AB%E3%83%90%E3%83%A0-%E8%8B%A5%E8%8F%9C%E7%BE%BD%E8%A1%A3-%E8%A5%BF%E6%9D%A1%E3%81%BB%E3%81%AE%E3%81%8B/dp/B01M7MDWJ3'),
('おジャ魔女どれみ', 'おじゃまじょどれみ', 'オジャマジョドレミ', '', 'Ojamajo Doremi', 'OJAMAJO DOREMI', 'ojamajo doremi', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS-8JMV9q22HsR79Bq6Zq-_3SFLXs09FQYMvWBEafsf-OZ6yLml', '名作『おジャ魔女どれみ』PASH! PLUS', 'https://www.pashplus.jp/anime/127768/'),
('お兄ちゃんだけど愛さえあれば関係ないよねっ', 'おにいちゃんだけどあいさえあればかんけいないよね', 'オニイチャンダケドアイサエアレバカンケイナイヨネ', '', 'OniAi', 'ONIANI', 'oniani', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR-Wg0ANRWJajpd97TRqDJvU15KAVGj3wEF_yZYBVEtzOJhyV5i', 'amazon.co.jp', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1-%E3%81%8A%E5%85%84%E3%81%A1%E3%82%83%E3%82%93%E3%81%A0%E3%81%91%E3%81%A9%E6%84%9B%E3%81%95%E3%81%88%E3%81%82%E3%82%8C%E3%81%B0%E9%96%A2%E4%BF%82%E3%81%AA%E3%81%84%E3%82%88%E3%81%AD%E3%81%A3-%E3%81%95%E3%82%93%E3%81%A8%E3%82%89-%E6%9C%80%E9%AB%98%E3%81%AE%E9%9F%B3%E6%A5%BD%E3%81%A0%E3%81%8B%E3%82%89%E3%81%A8%E3%81%AB%E3%81%8B%E3%81%8F%E8%81%9E%E3%81%84%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84%E3%82%B5%E3%83%B3%E3%83%88%E3%83%A9%E3%81%A0%E3%82%88%E3%81%AD%E3%81%A3-TV%E3%82%B5%E3%83%B3%E3%83%88%E3%83%A9/dp/B009ACU8R4'),
('俺がお嬢様学校に「庶民サンプル」としてゲッツされた件', 'おれはおじょうさまがっこうにしょみんさんぷるとしてげっつされたけん', 'オレハオジョウサマガッコウニショミンサンプルトシテゲッツサレタケン', '庶民サンプル', 'Shomin Sample', 'SHOMIN SAMPLE', 'shomin sample', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQyGGCxWN6olKbA9hppOy1PYAY-2IA-rZTbfxEhxzHkPbLOGFpF', '【主題歌】「庶民サンプル」アニメイト', 'https://www.animate-onlineshop.jp/products/detail.php?product_id=1366742'),
('俺が好きなのは妹だけど妹じゃない', 'おれがすきなのはいもうとだけどいもうとじゃない', 'オレガスキナノハイモウトダケドイモウトジャナイ', '', 'My Sister, My Writer', 'MY SISTER, MY WRITER', 'my sister, my writer', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS6nirjzRIVjvaDc0xza-6-2-Um41QmJJcQzS_DJz7PXP97QAYv', 'Amazon 俺が好きなのは妹だけど妹じゃないオリジナル・サウンドトラック', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8E%E4%BF%BA%E3%81%8C%E5%A5%BD%E3%81%8D%E3%81%AA%E3%81%AE%E3%81%AF%E5%A6%B9%E3%81%A0%E3%81%91%E3%81%A9%E5%A6%B9%E3%81%98%E3%82%83%E3%81%AA%E3%81%84%E3%80%8F%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF-%E3%82%84%E3%81%97%E3%81%8D%E3%82%93/dp/B07J2LRVYL'),
('俺の妹がこんなに可愛いわけがない', 'おれのいもうとがこんなにかわいいわけがない', 'オレノイモウトガコンナニカワイイワケガナイ', '俺妹', 'Oreimo', 'OREIMO', 'oreimo', 'https://images-na.ssl-images-amazon.com/images/I/61SnV%2BRsS0L.jpg', 'Amazon.co.jp', 'https://www.amazon.co.jp/%E4%BF%BA%E3%81%AE%E5%A6%B9%E3%81%8C%E3%81%93%E3%82%93%E3%81%AA%E3%81%AB%E5%8F%AF%E6%84%9B%E3%81%84%E3%82%8F%E3%81%91%E3%81%8C%E3%81%AA%E3%81%84%E3%80%82Complete-Collection-%E4%BF%BA%E5%A6%B9%E3%80%82%E3%82%B3%E3%83%B3%E3%83%97-%E4%BF%BA%E3%81%AE%E5%A6%B9%E3%81%8C%E3%81%93%E3%82%93%E3%81%AA%E3%81%AB%E5%8F%AF%E6%84%9B%E3%81%84%E3%82%8F%E3%81%91%E3%81%8C%E3%81%AA%E3%81%84%E3%80%82/dp/B01N6WEA6A'),
('俺の彼女と幼なじみが修羅場すぎる', 'おれのかのじょとおさななじみがしゅらばすぎる', 'オレノカノジョトオサナナジミガシュラバスギル', '俺修羅', 'Oreshura', 'ORESHURA', 'oreshura', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRT4J9-WweXw2ndlAs2GeoReZX0Msq_u-XwghqHojTS6HE89hy2', '『俺修羅』ヒロイン全員登場！アニメイトタイムズ', 'https://www.animatetimes.com/news/details.php?id=1360814268'),
('俺の脳内選択肢が、学園ラブコメを全力で邪魔している', 'おれののうないせんたくしががくえんらぶこめをぜんりょくでじゃましている', 'オレノノウナイセンタクシガガクエンラブコメヲゼンリョクデジャマシテイル', 'のうコメ', 'Noucome', 'NOUCOME', 'noucome', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQMMrSi5N-kXTZONj_t_oByP0XI4jMiupMc079zjTm5mPmFJ-Sx', '俺の脳内選択肢が、学園ラブコメを全力で邪魔している設定資料集', 'https://diomedea-shop.com/SHOP/DIO-NOC-01.html'),
('俺物語!!', 'おれものがたり', 'オレモノガタリ', '', 'My Love Story!!', 'MY LOVE STORY', 'my love story', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTzwgz9Kw9IgKxMrh5Xjgh2gu_VZhuXf40Vb5pMosNAxrjpPiQf', 'アルコ・河原和音/集英社 ', 'https://www.oricon.co.jp/news/2053330/photo/2/'),
('俺を好きなのはお前だけかよ', 'おれをすきなのはおまえだけかよ', 'オレヲスキナノハオマエダケカヨ', '俺好き', 'Oresuki', '', '', 'https://pbs.twimg.com/media/EHJj44YUYAA7IyG?format=jpg&name=medium', '公式Twitter', 'https://twitter.com/oresuki_anime/media'),
('終わりのセラフ', 'おわりのせらふ', 'オワリノセラフ', '', 'Seraph of the End', 'SERAPH OF THE END', 'seraph of the end', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSSe_fCV6jCjAvMvEbeiGYzfykmjvnW9mCUDOAsL4gyI8JGsW3z', 'ジャンプSQ.│『終わりのセラフ』', 'https://jumpsq.shueisha.co.jp/rensai/owarinoseraph/'),
('かぐや様は告らせたい〜天才たちの恋愛頭脳戦〜', 'かぐやさまはこくらせたい', 'カグヤサマハコクラセタイ', '', 'Kaguya-sama: Love Is War', 'KAGUYA-SAMA: LOVE IS WAR', 'kaguya-sama: love is war', 'https://youngjump.jp/kaguyasama/assets/img/main/img_main_sp.png', '原作公式サイト', 'https://youngjump.jp/kaguyasama/'),
('会長はメイド様！', 'かいちょうはめいどさま', 'カイチョウハメイドサマ', '', 'Maid-sama!', 'MAID-SAMA', 'maid-sama', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSiFVpr2u6TgfZYGSK_cAKDcnzsb4d2F41WPuCkmnWRRfz_9_6N', '会長はメイド様！| AT-X', 'https://www.at-x.com/program/detail/3195'),
('家庭教師ヒットマンREBORN！', 'かてきょうひっとまんりぼーん', 'カテキョウヒットマンリボーン', '', 'Reborn!', 'REBORN', 'reborn', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR1lh1ZYSLx4UQFyu-W7guyWH5DuTP9E43Mfv0fdF5mii7EteRY', 'Amazon|「家庭教師ヒットマンREBORN!」', 'https://www.amazon.co.jp/%E6%B1%BA%E5%AE%9A%E7%9B%A4%E3%80%8C%E5%AE%B6%E5%BA%AD%E6%95%99%E5%B8%AB%E3%83%92%E3%83%83%E3%83%88%E3%83%9E%E3%83%B3REBORN-%E3%80%8D%E3%82%A2%E3%83%8B%E3%83%A1%E4%B8%BB%E9%A1%8C%E6%AD%8C-%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E4%B8%BB%E9%A1%8C%E6%AD%8C%E3%82%AB%E3%83%90%E3%83%BC%E9%9B%86-VARIOUS-ARTISTS/dp/B071H6SJQQ'),
('彼方のアストラ', 'かなたのあすとら', 'カナタノアストラ', '', 'ASTRA LOST IN SPACE', 'ASTRA LOST IN SPACE', 'astra lost in space', 'http://astra-anime.com/assets/top/kv1_2b.png', '公式サイト', 'http://astra-anime.com/'),
('学戦都市アスタリスク', 'がくせんとしあすたりすく', 'ガクセントシアスタリスク', '', 'The Asterisk War', 'THE ASTERISK WAR', 'the asterisk war', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRmFzZn7Iqx5o6A0HmYQm4xoy704CKwMvRUeQLlndJ221YtoCb9', '【Blu-ray】学戦都市アスタリスク アニメイト', 'https://www.animate-onlineshop.jp/pn/%E3%80%90Blu-ray%E3%80%91TV%20%E5%AD%A6%E6%88%A6%E9%83%BD%E5%B8%82%E3%82%A2%E3%82%B9%E3%82%BF%E3%83%AA%E3%82%B9%E3%82%AF%202nd%20season%206%20%E5%AE%8C%E5%85%A8%E7%94%9F%E7%94%A3%E9%99%90%E5%AE%9A%E7%89%88/pd/1360294/'),
('がっこうぐらし！', 'がっこうぐらし', 'ガッコウグラシ', '', 'School-Live!', 'SCHOOL-LIVE', 'school-live', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSt9tpMBdzatffHvap_1QILy9zrlZguMnJClJey5QPqTy2-5nqb', 'amazon.co.jp がっこうぐらし!', 'https://www.amazon.co.jp/%E3%81%8C%E3%81%A3%E3%81%93%E3%81%86%E3%81%90%E3%82%89%E3%81%97-TV%E3%82%A2%E3%83%8B%E3%83%A1%E5%85%AC%E5%BC%8F%E3%82%AC%E3%82%A4%E3%83%89%E3%83%96%E3%83%83%E3%82%AF-%E5%AD%A6%E5%9C%92%E7%94%9F%E6%B4%BB%E9%83%A8%E6%B4%BB%E5%8B%95%E8%A8%98%E9%8C%B2-%E3%81%BE%E3%82%93%E3%81%8C%E3%82%BF%E3%82%A4%E3%83%A0KR%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9-%E3%83%95%E3%82%A9%E3%83%AF%E3%83%BC%E3%83%89%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA/dp/4832246461'),
('君に届け', 'きみにとどけ', 'キミニトドケ', '', 'From Me to You', 'FROM ME TO YOU', 'from me to you', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTGgVc9ciwzdH9A_3HGjmiWl6BlxEXT7HzmuW0jutwyT0d5-ZpN', '君に届け Vol.8 [DVD]', 'https://www.amazon.co.jp/%E5%90%9B%E3%81%AB%E5%B1%8A%E3%81%91-Vol-8-DVD-%E8%83%BD%E7%99%BB%E9%BA%BB%E7%BE%8E%E5%AD%90/dp/B003N4QB08'),
('クズの本懐', 'くずのほんかい', 'クズノホンカイ', '', "Scum's Wish", "SCUM'S WISH", "scum's wish", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTVTP-BUGTVjmvUgQAiuE1iOwLOmMZ1ifCB8n-c74IY5OhNblFy', '「クズの本懐」オフィシャルサイト', 'http://www.kuzunohonkai.com/'),
('雲のむこう、約束の場所', 'くものむこうやくそくのばしょ', 'クモノムコウヤクソクノバショ', '', 'The place promised in our early days', 'THE PLACE PROMISED IN OUR EARLY DAYS', 'the place promised in our early days', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQQww2sloOQwV6vrNuSxj_KVhsenNWxM-JBvYXgYDtcNCjm0CXk', 'Amazon 雲のむこう、約束の場所', 'https://www.amazon.co.jp/%E9%9B%B2%E3%81%AE%E3%82%80%E3%81%93%E3%81%86%E3%80%81%E7%B4%84%E6%9D%9F%E3%81%AE%E5%A0%B4%E6%89%80-DVD-%E5%90%89%E5%B2%A1%E7%A7%80%E9%9A%86/dp/B000793FBK'),
('黒子のバスケ', 'くろこのばすけ', 'クロコノバスケ', '黒バス', "Kuroko's Basketball", "KUROKO'S BASKETBALL", "kuroko's basketball", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQKqRyi3-dt4XOjGoJKiFr1SGKDDOEZmr5-Y2-F7OwzCkLm6THl', '黒子のバスケ アニメ！アニメ！', 'https://animeanime.jp/article/2014/10/20/20553.html'),
('グリザイアの果実', 'ぐりざいあのかじつ', 'グリザイアノカジツ', '', 'The Fruit of Grisaia', 'THE FRUIT OF GRISAIA', 'the fruit of grisaia', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRGd3EoeJGExOo6YdtQsyerL9nhwikXNNy3FEeQL8S2nO0_p6fZ', 'グリザイアの果実 | ヤマダウェブコム', 'https://www.yamada-denkiweb.com/2814570014'),
('月刊少女野崎くん', 'げっかんしょうじょのざきくん', 'ゲッカンショウジョノザキクン', '', "Monthly Girls' Nozaki-kun", "MONTHLY GIRLS' NOZAKI-KUN", "monthly girls' nozaki-kun", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSyjEZsRnVGnfFjTTUxWwKOAThCWKlVRVoMXZ-AYix3VqswrhxA', '月刊少女野崎くん SQUARE ENIX', 'https://www.ganganonline.com/contents/nozaki/'),
('恋と嘘', 'こいとうそ', 'コイトウソ', '', 'LOVE and LIES', 'LOVE AND LIES', 'love and lies', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSmJyZZ8SeMuq2YJYaeRL2hGnJTW-c3fzUCkMMQmhyrCobe_MH8', '『恋と嘘』アニメイトタイムズ', 'https://www.animatetimes.com/news/details.php?id=1496747683'),
('恋は雨上がりのように', 'こいはあめあがりのように', 'コイハアメアガリノヨウニ', '', 'After the Rain', 'AFTER THE RAIN', 'after the rain', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRu3I13pmlTDLrKCfCrRmNzdTJ5G0XpBmF0ooZ6__e8ILTRGu82', 'Amazon 恋は雨上がりのように', 'https://www.amazon.co.jp/dp/B00UV9VIVU/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1'),
('心が叫びたがってるんだ。', 'こころがさけびたがってるんだ', 'ココロガサケビタガッテルンダ', 'ここさけ', 'The Anthem of the Heart', 'THE ANTHEM OF THE HEART', 'the anthem of the heart', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSoBT3ASlwm4QXNjDMGQ5lPuPAhhfseY2NrUc6YbRoz4EQ68rZn', 'アニメ映画『心が叫びたがってるんだ。』', 'https://www.kokosake.jp/'),
('言の葉の庭', 'ことのはのには', 'コトノハノニワ', '', 'The Garden of Words', 'THE GARDEN OF WORDS', 'the garden of words', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRvOSiC2BJIcJ2C785rnFKqv7-Yo7YZKi_2WMZVtYnLxrK-W5zy', '言の葉の庭', 'https://www.kotonohanoniwa.jp/'),
('この素晴らしい世界に祝福を！', 'このすばらしいせかいにしゅくふくを', 'コノスバラシイセカイニシュクフクヲ', 'このすば', "God's Blessing on this Wonderful World!", "GOD'S BLESSING ON THIS WONDERFUL WORLD!", "god's blessing on this wonderful world!", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSothb-B1GM8uZlc9QcXNQgsQDOskzWHr4I8tN1tECOgaap3fvQ', 'Amazon この素晴らしい世界に祝福を!', 'https://www.amazon.co.jp/%E3%81%93%E3%81%AE%E7%B4%A0%E6%99%B4%E3%82%89%E3%81%97%E3%81%84%E4%B8%96%E7%95%8C%E3%81%AB%E7%A5%9D%E7%A6%8F%E3%82%92-12-%E5%A5%B3%E9%A8%8E%E5%A3%AB%E3%81%AE%E3%83%A9%E3%83%A9%E3%83%90%E3%82%A4-%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%96%E3%83%AB%E3%83%BC%E3%83%AC%E3%82%A4%E4%BB%98%E3%81%8D%E5%90%8C%E6%A2%B1%E7%89%88-%E3%81%AA%E3%81%A4%E3%82%81/dp/4041050057'),
('小林さんちのメイドラゴン', 'こばやしさんちのめいどらごん', 'コバヤシサンチノメイドラゴン', '', "Miss Kobayashi's Dragon Maid", "MISS KOBAYASHI'S DRAGON MAID", "miss kobayashi's dragon maid", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSnUgkp3X0BS_x444V6bkMop5UluMQV8O8WhKKjMqDyugwDuJxl', '「小林さんちのメイドラゴン」公式サイト', 'http://maidragon.jp/'),
('五等分の花嫁', 'ごとうぶんのはなよめ', 'ゴトウブンノハナヨメ', '', 'The Quintessential Quintuplets', 'THE QUINTESSENTIAL QUINTUPLETS', 'the quintessential quintuplets', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSDlZGQVBRRJ-hcDTqwXEpkR43BnuTPCS-h_H_AND_tWV7aI5fF', 'Amazon 「五等分の花嫁」', 'https://www.amazon.co.jp/%E3%80%8C%E4%BA%94%E7%AD%89%E5%88%86%E3%81%AE%E8%8A%B1%E5%AB%81%E3%80%8D%E3%82%AD%E3%83%A3%E3%83%A9%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%BD%E3%83%B3%E3%82%B0-%E3%83%9F%E3%83%8B%E3%82%A2%E3%83%AB%E3%83%90%E3%83%A0-%E4%B8%AD%E9%87%8E%E5%AE%B6%E3%81%AE%E4%BA%94%E3%81%A4%E5%AD%90-%E8%8A%B1%E6%BE%A4%E9%A6%99%E8%8F%9C%E3%83%BB%E7%AB%B9%E9%81%94%E5%BD%A9%E5%A5%88%E3%83%BB%E4%BC%8A%E8%97%A4%E7%BE%8E%E6%9D%A5%E3%83%BB%E4%BD%90%E5%80%89%E7%B6%BE%E9%9F%B3%E3%83%BB%E6%B0%B4%E7%80%AC%E3%81%84%E3%81%AE%E3%82%8A/dp/B07KRBL9XN'),
('極黒のブリュンヒルデ', 'ごくこくのぶりゅんひるで', 'ゴクコクノブリュンヒルデ', '', 'Brynhildr in the Darkness', 'BRYNHILDR IN THE DARKNESS', 'brynhildr in the darkness', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQkQqREWO2ccpZ490zM1KM6GFV8yW_mH_XfH_u1lUlw_5OA2Xvo', '極黒のブリュンヒルデ｜アニメ広場', 'https://www.anime-hiroba.com/anime/gokukoku-no-brynhildr/'),
('冴えない彼女の育てかた', 'さえないかのじょのそだてかた', 'サエナイカノジョノソダテカタ', '冴えカノ', 'How to Raise a Boring Girlfriend', 'HOW TO RAISE A BORING GIRLFRIEND', 'how to raise a boring girlfriend', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQGTcCKsnInnMrmcMyf1eSFvh9kFK7PO0YOEsN0v-tL6ac7d6s6', '冴えない彼女の育てかた13 | KADOKAWA', 'https://www.kadokawa.co.jp/product/321702000733/'),
('さくら荘のペットな彼女', 'さくらそうのぺっとなかのじょ', 'サクラソウノペットナカノジョ', '', 'The Pet Girl of Sakurasou', 'THE PET GIRL OF SAKURASOU', 'the pet girl of sakurasou', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSiwgJb0NPUnCJEMS_Xt9uF4YCH26MFtoQAHsMeIAYd44pOmYcb', 'さくら荘のペットな彼女｜アニメ｜日テレプラス', 'https://www.nitteleplus.com/program/anime/sakurasou.html'),
('四月は君の嘘', 'しがつはきみのうそ', 'シガツハキミノウソ', '君嘘', 'Your lie in April', 'YOUR LIE IN APRIL', 'your lie in april', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSb-BC-tGwC9pXQQVhLRPLzw0-PENQpqgSLasX8YyMmSZsoWkE7', '四月は君の嘘 3 | ANIPLEX+', 'https://www.aniplexplus.com/itemRLSmZCWd'),
('下ネタという概念が存在しない退屈な世界', 'しもねたというがいねんがそんざいしないたいくつなせかい', 'シモネタトイウガイネンガソンザイシナイタイクツナセカイ', '', "A Boring World Where the Concept of Dirty Jokes Doesn't Exist", "A BORING WORLD WHERE THE CONCEPT OF DIRTY JOKES DOESN'T EXIST", "a boring world where the concept of dirty jokes doesn't exist", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSdUGToYSiF9Vv9sPWJ_1fNVxS1uoE0zt00EV_Qg1RULV3BK5gZ', 'Amazon', 'https://www.amazon.co.jp/%E4%B8%8B%E3%83%8D%E3%82%BF%E3%81%A8%E3%81%84%E3%81%86%E6%A6%82%E5%BF%B5%E3%81%8C%E5%AD%98%E5%9C%A8%E3%81%97%E3%81%AA%E3%81%84%E9%80%80%E5%B1%88%E3%81%AA%E4%B8%96%E7%95%8C-%E3%83%9E%E3%83%B3%E2%97%8F%E7%AF%87-1%E5%B7%BB-%E3%83%96%E3%83%AC%E3%82%A4%E3%83%89%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9-%E8%B5%A4%E5%9F%8E%E5%A4%A7%E7%A9%BA-ebook/dp/B00U0U8O0S'),
('灼眼のシャナ', 'しゃくがんのしゃな', 'シャクガンノシャナ', '', 'Shakugan no Shana', 'SHAKUGAN NO SHANA', 'shakugan no shana', 'https://www.shakugan.com/core_sys/images/contents/00000309/block/00000401/00000637.jpg?1555161169', '「灼眼のシャナⅢ-FINAL-」公式サイト-', 'https://www.shakugan.com/contents/hp0021/index03090000.html'),
('青春ブタ野郎はバニーガール先輩の夢を見ない', 'せいしゅんぶたやろうはばにーがーるせんぱいのゆめをみない', 'セイシュンブタヤロウハバニーガールセンパイノユメヲミナイ', '', 'Rascal Does Not Dream of Bunny Girl Senpai', 'RASCAL DOES NOT DREAM OF BUNNY GIRL SENPAI', 'rascal does not dream of bunny girl senpai', 'https://ao-buta.com/assets/img/book/tmb_book01.jpg', '「青春ブタ野郎はバニーガール先輩の夢を見ない」公式サイト', 'https://ao-buta.com/book/?movie'),
('絶園のテンペスト', 'ぜつえんのぺんてすと', 'ゼツエンノペンテスト', '', 'Blast of Tempest', 'BLAST OF TEMPEST', 'blast of tempest', 'https://www.zetsuen.net/common/img/top/main.png', 'TVアニメ「絶園のテンペスト」', 'https://www.zetsuen.net/'),
('ゼロの使い魔', 'ぜろのつかいま', 'ゼロノツカイマ', 'ゼロ魔', 'The Familiar of Zero', 'THE FAMILIAR OF ZERO', 'the familiar of zero', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRi3crRA1gyKO0i9bpkyB-0isDH9jRQzQET-wpdyw_XiMZAXvh8', '『ゼロの使い魔』アニメイトタイムズ', 'https://www.animatetimes.com/news/details.php?id=1512106530'),
('空の青さを知る人よ', 'そらのあおさをしるひとよ', 'ソラノアオサヲシルヒトヨ', 'Her Blue Sky', 'Her Blue Sky', 'HER BLUE SKY', 'her blue sky', 'https://www.clubdam.com/app/dam/image/598/img.jpg', '映画『空の青さを知る人よ』', 'https://www.clubdam.com/app/dam/dam/special_detail.html?feature_id=598'),
('盾の勇者の成り上がり', 'たてのゆうしゃのなりあがり', 'タテノユウシャノナリアガリ', '', 'The Rising of the Shield Hero', 'THE RISING OF THE SHIELD HERO', 'the rising of the shield hero', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRsB-bG7A03-1WazHMnaeo99B8oO2-9OXf520w6AF72mB2J5nwJ', '盾の勇者の成り上がり ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_MF01000012010000_68/'),
('中二病でも恋がしたい！', 'ちゅうにびょうでもこいがしたい', 'チュウニビョウデモコイガシタイ', '', 'Love, Chunibyo & Other Delusions', 'LOVE, CHUNIBYO & OTHER DELUSIONS', 'love, chunibyo & other delusions', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRchoEzecoVFDPKq2FrP0hMk_8o-BuGVXwYU9f705oVwRhIaMDL', '『中二病でも恋がしたい！』KAエスマ文庫', 'http://www.kyotoanimation.co.jp/books/chuunibyo/'),
('ダンベル何キロ持てる？', 'だんべるなんきろもてる', 'ダンベルナンキロモテル', '', 'How Many Kilograms of Dumbbell Can You Lift?', 'HOW MANY KILOGRAMS OF DUMBBELL CAN YOU LIFT?', 'how many kilograms of dumbbell can you lift?', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTjvGmTfy9lqcOqhkdm2pi6pRmVh7S8ttoU6ODmUAneKO0MpfOH', 'Amazon ダンベル何キロ持てる?', 'https://www.amazon.co.jp/%E3%83%80%E3%83%B3%E3%83%99%E3%83%AB%E4%BD%95%E3%82%AD%E3%83%AD%E6%8C%81%E3%81%A6%E3%82%8B-Vol-4-DVD-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%83%BC%E3%82%BA%E3%81%82%E3%81%84/dp/B07TQGS3PV'),
('テニスの王子様', 'てにすのおうじさま', 'テニスノオウジサマ', 'テニプリ', 'The Prince of Tennis', 'THE PRINCE OF TENNIS', 'the prince of tennis', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRzoQ7WE4smm7-ZXQ8ovgCUKSVnHVfxF7En7D8n5l1JdnGfrVt2', '(c)許斐 剛／集英社・NAS・新テニスの王子様プロジェクト', 'https://spice.eplus.jp/articles/153662'),
('転生したらスライムだった件', 'てんせいしたらすらいむだったけん', 'テンセイシタラスライムダッタケン', '転スラ', 'That Time I Got Reincarnated as a Slime', 'THAT TIME I GOT REINCARNATED AS A SLIME', 'that time i got reincarnated as a slime', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcReJAUQiYLXwKDahVsuZeNHCdu5J8YVhh65mE8IRf5j9hYnQhvf', '「転生したらスライムだった件」公式サイト', 'http://www.ten-sura.com/'),
('亜人ちゃんは語りたい', 'でみちゃんはかたりたい', 'デミチャンハカタリタイ', '', 'Interviews with Monster Girls', 'INTERVIEWS WITH MONSTER GIRLS', 'interviews with monster girls', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSfI4t1b6f8DpjGp0-rnzs6pDZ815CEx_aSUe9JJfSYmqPROQVI', '「亜人ちゃんは語りたい」公式サイト', 'https://demichan.com/'),
('とある魔術の禁書目録', 'とあるまじゅつのいんでっくす', 'トアルマジュツノインデックス', '', 'A Certain Magical Index', 'A CERTAIN MAGICAL INDEX', 'a certain magical index', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRBS8WMQsSHtH6HsUNLUqmSvFnKSEPX01h_fHHngYiLTbE6tx31', '「とある魔術の禁書目録Ⅲ」UtaTen', 'https://utaten.com/specialArticle/index/3423'),
('とある科学の超電磁砲', 'とあるかがくのれーるがん', 'トアルカガクノレールガン', '', 'A Certain Scientific Railgun', 'A CERTAIN SCIENTIFIC RAILGUN', 'a certain scientific railgun', 'https://cdn.utaten.com/uploads/images/specialArticle/4140/thumbnail/0x1000/55979589a46970178be1395308141ea434f2bac1.jpeg', '「とある科学の超電磁砲」UtaTen', 'https://utaten.com/specialArticle/index/4140'),
('とある科学の一方通行', 'とあるかがくのあくせられーた', 'トアルカガクノアクセラレータ', '', 'A Certain Scientific Accelerator', 'A CERTAIN SCIENTIFIC ACCELERATOR', 'a certain scientific accelerator', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSN5o1UvB6dI67o-jD_wyZlS0xao8CRm8sLicDFN9sG8KJ8MxyU', 'とある科学の一方通行 アニメ公式サイト', 'https://toaru-project.com/accelerator/'),
('となりの関くん', 'となりのせきくん', 'トナリノセキクン', '', 'The Master of Killing Time', 'THE MASTER OF KILLING TIME', 'the master of killing time', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQx58ae5bM5JIs9I_KwA5wPfl5HlitkiyvB8gCmBqeQN6pagfMq', 'となりの関くん ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_MF01000001010000_68/'),
('とらドラ!', 'とらどら', 'トラドラ', '', 'Toradora!', 'TORADORA!', 'toradora!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSb90-7tJXUcjSv7XvXdDw_XqeboPPq1dafNGz2tgLC_6uPmbUx', 'とらドラ！ ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_AM05000021010000_68/'),
('七つの大罪', 'ななつのたいざい', 'ナナツノタイザイ', '', 'The Seven Deadly Sins', 'THE SEVEN DEADLY SINS', 'the seven deadly sins', 'https://cdn-ak.f.st-hatena.com/images/fotolife/s/shonenmagazine/20190902/20190902001148.jpg', '「七つの大罪」 週マガ公式サイト', 'https://shonenmagazine.com/info/entry/20190903taizai'),
('ネトゲの嫁は女の子じゃないと思った？', 'ねとげのよめはおんなのこじゃないとおもった', 'ネトゲノヨメハオンナノコジャナイトオモッタ', 'ネトゲの嫁', 'And You Thought There Is Never a Girl Online?', 'AND YOU THOUGHT THERE IS NEVER A GIRL ONLINE?', 'and you thought there is never a girl online?', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ0TZx-B_IWAX0LGbZNiHqnx9D1xQ4G4L_uXFfGgHkVo4C4Dy2A', 'TVアニメ 公式サイト', 'https://netogenoyome.com/'),
('ノラガミ', 'のらがみ', '', '', 'Noragami: Stray God', 'NORAGAMI: STRAY GOD', 'noragami: stray god', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxk2zGcByql8vbCUhURBdfiwuruvrsL9AJMCAIQ_ZXS1ZIbI1S', '「ノラガミ ARAGOTO」公式サイト', 'https://noragami-anime.net/'),
('鋼の錬金術師', 'はがねのれんきんじゅつし', 'ハガネノレンキンジュツシ', 'ハガレン', 'Fullmetal Alchemist', 'FULLMETAL ALCHEMIST', 'fullmetal alchemist', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRjJBuLkNY1bJK-UBeaFRfm6Z8JUPrlecBoz1j5ApIjXr0sfTfL', '鋼の錬金術師 Blu-ray Disc Box', 'https://www.hagaren.jp/fa/'),
('はじめの一歩', 'はじめのいっぽ', 'ハジメノイッポ', '', 'Hajime no Ippo', 'HAJIME NO IPPO', 'hajime no ippo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS14-f0sUKL8f5diD0rJKAYZTYL3CGQyctGEDFu7jsnF55d7UyG', 'Amazon はじめの一歩(124)', 'https://www.amazon.co.jp/%E3%81%AF%E3%81%98%E3%82%81%E3%81%AE%E4%B8%80%E6%AD%A9-124-%E8%AC%9B%E8%AB%87%E7%A4%BE%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9-%E6%A3%AE%E5%B7%9D-%E3%82%B8%E3%83%A7%E3%83%BC%E3%82%B8/dp/4065141273'),
('はたらく魔王さま！', 'はたらくまおうさま', 'ハタラクマオウサマ', '', 'The Devil Is a Part-Timer', 'THE DEVIL IS A PART-TIMER', 'the devil is a part-timer', 'http://aka.saintpillia.com/maousama/chara8.png', '『はたらく魔王さま！』公式サイト', 'http://maousama.jp/'),
('花咲くいろは', 'はなさくいろは', 'ハナサクイロハ', '', 'Hanasaku Iroha', 'HANASAKU IROHA', 'hanasaku iroha', 'http://www.hanasakuiroha.jp/img/top/img_catch_newkids03.jpg', '「TVシリーズ 花咲くいろは」公式サイト', 'http://www.hanasakuiroha.jp/tv/'),
('バカとテストと召喚獣', 'ばかとてすととしょうかんじゅう', 'バカトテストトショウカンジュウ', 'バカテス', 'Baka and Test Summon the Beasts', 'BAKA AND TEST SUMMON THE BEASTS', 'baka and test summon the beasts', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSJ248VSRou9nbfya6cbJGCoF5j4AAoU1gJLnG-xf-XbxV5jgpB', 'バカとテストと召喚獣(15)| KADOKAWA', 'https://www.kadokawa.co.jp/product/321606000431/'),
('ばらかもん', '', 'バラカモン', '', 'Barakamon', 'BARAKAMON', 'barakamon', 'https://www.vap.co.jp/barakamon/images/bd-dvd/bdbox/jacket.png', 'BD&DVD｜TVアニメ「ばらかもん」公式サイト', 'https://www.vap.co.jp/barakamon/bd-dvd/index.html'),
('緋弾のアリア', 'ひだんのありあ', 'ヒダンノアリア', '', 'Aria The Scarlet Ammo', 'ARIA THE SCARLET AMMO', 'aria the scarlet ammo', 'https://images-fe.ssl-images-amazon.com/images/I/512NtJFCZxL._SY346_.jpg', 'Amazon 緋弾のアリア (MF文庫J)', 'https://www.amazon.co.jp/dp/B0095F0AJC/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1'),
('火ノ丸相撲', 'ひのまるずもう', 'ヒノマルズモウ', '', 'Hinomaru Sumo', 'HINOMARU SUMO', 'hinomaru sumo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS7AG9CmEPnkBZ1G94aepSmJHk9_2thF4PG8abTvsYvhYT23I1h', 'アニメ「火ノ丸相撲」公式サイト', 'https://hinomaru-zumou.com/'),
('ヒナまつり', 'ひなまつり', 'ヒナマツリ', '', 'Hinamatsuri', 'HINAMATSURI', 'hinamatsuri', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQy-tvKAzYuOhk1kvQLvzowbYHqNJPr0JTmEjfavFa6cYwdestC', 'TVアニメ『ヒナまつり』公式サイト', 'http://hina-matsuri.net/'),
('秒速5センチメートル', 'びょうそくごせんちめーとる', 'ビョウソクゴセンチメートル', '', '5 Centimeters per Second', '5 CENTIMETERS PER SECOND', '5 centimeters per second', 'https://s.yimg.jp/images/evt/5cm/phg_9.jpg', '秒速5センチメートル', 'https://www.cwfilms.jp/5cm/gallery/9.html'),
('覆面系ノイズ', 'ふくめんけいのいず', 'フクメンケイノイズ', '', 'Anonymous Noise', 'ANONYMOUS NOISE', 'anonymous noise', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS0l8vI9w07raXyLCL4jYasPk7RGWUtTGoky9MSRX0T__CO44oD', 'TVアニメ『覆面系ノイズ』公式サイト', 'http://fukumenkei-anime.jp/'),
('文豪ストレイドッグス', 'ぶんごうすとれいどっぐす', 'ブンゴウストレイドッグス', '', 'Bungo Stray Dogs', 'BUNGO STRAY DOGS', 'bungo stray dogs', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScGJ4IXekgAgIEPtpijg7vBHDaGJwkuCY7hj2PIQqFcv9QvwQU', '文豪ストレイドッグス　ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_KS02000024010000_68/'),
('変態王子と笑わない猫。', 'へんたいおうじとわらわらないねこ', 'ヘンタイオウジトワラワナイネコ', '', 'The Hentai Prince and the Stony Cat', 'THE HENTAI PRINCE AND THE STONY CAT', 'the hentai prince and the stony cat', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSsRdhZtWqPk93hDbn2F9Jvn9M6pXFOknyHEdyWfI8NRBhfn-YL', '『変態王子と笑わない猫。』アニメイトタイムズ', 'https://www.animatetimes.com/news/details.php?id=1363914593'),
('僕だけがいない町', 'ぼくだけがいないまち', 'ボクダケガイナイマチ', '', 'The Town Where Only I Am Missing', 'THE TOWN WHERE ONLY I AM MISSING', 'the town where only i am missing', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQRxrTt-FCEQBRllsYd_w_jHjlxNxE9LDTPUcTq4Sgc40K9hsEr', '「僕だけがいない街」公式サイト', 'https://bokumachi-anime.com/'),
('星を追う子ども', 'ほしをおうこども', 'ホシヲオウコドモ', '', 'Children Who Chase Lost Voices', 'CHILDREN WHO CHASE LOST VOICES', 'children who chase lost voices', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQUQWgkoVfWETEV-lpIRZmmqvSVfGl4RFhz9c3kawAP0mWW7HXX', 'Amazon 星を追う子ども', 'https://www.amazon.co.jp/%E5%8A%87%E5%A0%B4%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3-%E6%98%9F%E3%82%92%E8%BF%BD%E3%81%86%E5%AD%90%E3%81%A9%E3%82%82-Original-SoundTrack-%E7%86%8A%E6%9C%A8%E6%9D%8F%E9%87%8C/dp/B004TTLZRU'),
('僕のヒーローアカデミア', 'ぼくのひーろーあかでみあ', 'ボクノヒーローアカデミア', 'ヒロアカ', 'My Hero Academia', 'MY HERO ACADEMIA', 'my hero academia', 'https://heroaca.com/images/common/s4_3_c_top_illust.jpg', 'TVアニメ『僕のヒーローアカデミア』', 'https://heroaca.com/'),
('僕は友達が少ない', 'ぼくはともだちがすくない', 'ボクハトモダチガスクナイ', 'はがない', 'Haganai', 'HAGANAI', 'haganai', 'https://www.tbs.co.jp/anime/haganai/1st/goods/images/disc00.jpg', '僕は友達が少ない 公式ホームページ', 'https://www.tbs.co.jp/anime/haganai/1st/goods/disc_1.html'),
('僕らはみんな河合荘', 'ぼくらはみんなかわいそう', 'ボクラハミンナカワイソウ', '', 'The Kawai Complex Guide to Manors and Hostel Behavior', 'THE KAWAI COMPLEX GUIDE TO MANORS AND HOSTEL BEHAVIOR', 'the kawai complex guide to manors and hostel behavior', 'https://www.tbs.co.jp/anime/kawaisou/disc/images/disc07.jpg', '僕らはみんな河合荘 Blu-ray&DVD 第7巻', 'https://www.tbs.co.jp/anime/kawaisou/disc/'),
('ボールルームへようこそ', 'ぼーるるーむへようこそ', 'ボールルームヘヨウコソ', '', 'Welcome to the Ballroom', 'WELCOME TO THE BALLROOM', 'welcome to the ballroom', 'http://ballroom-official.jp/wordpress/wp-content/themes/ballroom02/images/top_keyvisual05.png', 'TVアニメ「ボールルームへようこそ」公式サイト', 'http://ballroom-official.jp/'),
('政宗くんのリベンジ', 'まさむねくんのりべんじ', 'マサムネクンノリベンジ', '', "Masamune-kun's Revenge", "MASAMUNE-KUN'S REVENGE", "masamune-kun's revenge", 'http://masamune-tv.com/wp/wp-content/uploads/2017/02/MR07_144_T2.jpg', 'TVアニメ「政宗くんのリベンジ」公式サイト', 'http://masamune-tv.com/story/7'),
('魔法科高校の劣等生', 'まほうかこうこうのれっとうせい', 'マホウカコウコウノレットウセイ', 'おにいさま', 'The Irregular at Magic High School', 'THE IRREGULAR AT MAGIC HIGH SCHOOL', 'the irregular at magic high school', 'https://mahouka.jp/1st/img/bddvd/jk_vol1.jpg', 'アニメ『魔法科高校の劣等生』', 'https://mahouka.jp/1st/bddvd/vol1.html'),
('モンスター娘のいる日常', 'もんすたーむすめのいるにちじょう', 'モンスタームスメノイルニチジョウ', 'モン娘', 'Everyday Life with Monster Girls', 'EVERYDAY LIFE WITH MONSTER GIRLS', 'everyday life with monster girls', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcScOXAEl8TChc-2lu4E2IHFny84S0cWUTi3GsrPGyf5cM7GPFLC', 'Amazon モンスター娘のいる日常', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8C%E3%83%A2%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%BC%E5%A8%98%E3%81%AE%E3%81%84%E3%82%8B%E6%97%A5%E5%B8%B8%E3%80%8D%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF-manzo/dp/B01519FXBA'),
('山田くんと7人の魔女', 'やまだくんとしちにんのまじょ', 'ヤマダクントシチニンノマジョ', '', 'Yamada-kun and the Seven Witches', 'YAMADA-KUN AND THE SEVEN WITCHES', 'yamada-kun and the seven witches', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTYYMCjj5mjn_1_zMEBJSnV4RfJ0Lxdiv0MqaxZOZPgdPzMDenO', '「山田くんと7人の魔女」映画.com', 'https://eiga.com/news/20141204/1/'),
('ようこそ実力至上主義の教室へ', 'ようこそじつりょくしじょうしゅぎのきょうしつへ', 'ヨウコソジツリョクシジョウシュギノキョウシツヘ', 'よう実', 'Classroom of the Elite', 'CLASSROOM OF THE ELITE', 'classroom of the elite', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSX1bkgH-2OJoiIhlf9mTWiI2-pt5JdGY5bFESmLP-DzPFp_OT5', 'ようこそ実力至上主義の教室へ ComicWalker', 'https://comic-walker.com/contents/detail/KDCW_MF02000060010000_68/'),
('幼女戦記', 'ようじょせんき', 'ヨウジョセンキ', '', 'The Saga of Tanya the Evil', 'THE SAGA OF TANYA THE EVIL', 'the saga of tanya the evil', 'https://images-fe.ssl-images-amazon.com/images/I/61A2Gs3tX3L._SY346_.jpg', 'Amazon 幼女戦記(1)', 'https://www.amazon.co.jp/%E5%B9%BC%E5%A5%B3%E6%88%A6%E8%A8%98-1-%E8%A7%92%E5%B7%9D%E3%82%B3%E3%83%9F%E3%83%83%E3%82%AF%E3%82%B9%E3%83%BB%E3%82%A8%E3%83%BC%E3%82%B9-%E6%9D%B1%E6%A2%9D-%E3%83%81%E3%82%AB-ebook/dp/B01N671G49'),
('弱虫ペダル', 'よわむしぺだる', 'ヨワムシペダル', '弱ペダ', 'Yowamushi Pedal', 'YOWAMUSHI PEDAL', 'yowamushi pedal', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcT45PHoqxLE6XCYOGcJ_0V5Hi0GdrVV0qjbhK6kpd1IFoxqhWkT', 'TVアニメ『弱虫ペダル GLORY LINE』 公式サイト', 'http://yowapeda.com/'),
('Re:ゼロから始める異世界生活', 'りぜろからはじめるいせかいせいかつ', 'リゼロカラハジメルイセカイセイカツ', 'リゼロ', 'Re:Zero -Starting Life in Another World-', 'RE:ZERO -STARTING LIFE IN ANOTHER WORLD-', 're:zero -starting life in another world-', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQJBlcSjL7jBt8MRSjsvkCr-MhZ0V9j3c_thdn8sOAR19669BNp', '4月アニメ「リゼロ」ザテレビジョン', 'https://thetv.jp/news/detail/75189/'),
('りゅうおうのおしごと！', '', 'リュウオウノオシゴト！', "", "The Ryuo's Work is Never Done", "THE RYUO'S WORK IS NEVER DONE", "the ryuo's work is never done", 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSKWuVL4uIv4XvlVHYSYxqSQf0e0PfDtzJXw7_y4ednu5yo2jmz', 'TVアニメ『りゅうおうのおしごと! 』オリジナル・サウンドトラック', 'https://www.amazon.co.jp/TV%E3%82%A2%E3%83%8B%E3%83%A1%E3%80%8E%E3%82%8A%E3%82%85%E3%81%86%E3%81%8A%E3%81%86%E3%81%AE%E3%81%8A%E3%81%97%E3%81%94%E3%81%A8-%E3%80%8F%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF-%E9%9F%B3%E6%A5%BD-%E5%B7%9D%E4%BA%95%E6%86%B2%E6%AC%A1/dp/B079LC63S6'),
('私がモテないのはどう考えてもお前らが悪い！', 'わたしがもてないのはどうかんがえてもおまえらがわるい', 'ワタシガモテナイノハドウカンガエテモオマエラガワルイ', 'わたもて', 'No Matter How I Look at It, It’s You Guys’ Fault I’m Not Popular!', 'NO MATTER HOW I LOOK AT IT, IT’S YOU GUYS’ FAULT I’M NOT POPULAR!', 'no matter how i look at it, it’s you guys’ fault i’m not popular!', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTEuIvVjVYQSeFxbvTKE_9tPoyKIqZ2EjLOlBmd2fWsCdi3n7F1', '私がモテないのはどう考えてもお前らが悪い！', 'http://www.watamote.jp/'),
('君の名は。', 'きみのなは', 'キミノナハ', '', 'Your Name.', 'YOUR NAME', 'your name', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ63FXpvACQnnLNUTl6u_z4JywO6vIqgYY11zuMc7CasS2YrNag', '映画『君の名は。』公式サイト', 'http://www.kiminona.com/'),
('からかい上手の高木さん', 'からかいじょうずのたかぎさん', 'カラカイジョウズノタカギサン', '', 'Teasing Master Takagi-san', 'TEASING MASTER TAKAGI-SAN', 'teasing master takagi-san', 'http://takagi3.me/images/story/intro_main.png', '「からかい上手の高木さん②」公式サイト', 'http://takagi3.me/story/introduction.php');
-- ('異世界魔王と召喚少女の奴隷魔術', '', '', '', 'How Not to Summon a Demon Lord', '', '', '', '', ''),
-- ('イタズラなKiss', '', '', '', 'Itazura Na Kiss', '', '', '', '', ''),
-- ('苺ましまろ', '', '', '', 'Strawberry Marshmallow', '', '', '', '', ''),
-- ('いちばんうしろの大魔王', '', '', '', 'Demon King Daimao', '', '', '', '', ''),
-- ('一騎当千', '', '', '', 'Great Guardians', '', '', '', '', ''),
-- ('いつかの天魔の黒ウサギ', '', '', '', 'Itsuka Tenma no Kuro Usagi', '', '', '', '', ''),
-- ('いなり、こんこん、恋いろは。', '', '', '', 'Inari Kon Kon Essentials', '', '', '', '', ''),
-- ('犬とハサミは使いよう', '', '', '', 'Dog & Scissors', '', '', '', '', ''),
-- ('妖狐×僕SS', '', '', '', 'Inu×Boku', '', '', '', '', ''),
-- ('失われた未来を求めて', '', '', '', 'In Search of the Lost Future ', '', '', '', '', ''),
-- ('うたの☆プリンスさまっ♪マジLOVE1000%', '', '', 'うた☆プリ', 'Uta no prince sama Maji love 1000%', '', '', '', '', ''),
-- ('うたわれるもの', '', '', '', 'Utawarerumono', '', '', '', '', ''),
-- ('宇宙戦艦ティラミス', '', '', '', 'Space Battleship Tiramisu', '', '', '', '', ''),
-- ('ウマ娘', '', '', '', 'Uma Musume Pretty Derby', '', '', '', '', ''),
-- ('うみねこなく頃に', '', '', '', 'Umineko: When They Cry', '', '', '', '', ''),
-- ('裏切りは僕の名前を知っている', '', '', '', 'The Betrayal Knows My Name ', '', '', '', '', ''),
-- ('衛宮さんちの今日のごはん', '', '', '', "Today's Menu for the Emiya Family", '', '', '', '', ''),
-- ('桜蘭高校ホスト部', '', '', '', 'Ouran High School Host Club', '', '', '', '', ''),
-- ('狼と香辛料', '', '', '', 'Spice And Wolf', '', '', '', '', ''),
-- ('大家さんは思春期！', '', '', '', 'Ooya-san wa Shishunki!', '', '', '', '', ''),
-- ('おしえて！ギャル子ちゃん', '', '', '', 'Please Tell Me! Galko-chan', '', '', '', '', ''),
-- ('おじゃる丸', '', '', '', 'Ojarumaru', '', '', '', '', ''),
-- ('織田信奈の野望', '', '', '', 'Ambition of Oda Nobuna', '', '', '', '', ''),
-- ('大人の防具屋さん', '', '', '', 'Armor Shop for Ladies & Gentlemen', '', '', '', '', ''),
-- ('おとめ妖怪 ざくろ', '', '', '', 'Otome Youkai Zakuro', '', '', '', '', ''),
-- ('お姉ちゃんが来た', '', '', '', 'Oneechan ga Kita', '', '', '', '', ''),
-- ('おねがいマイメロディ', '', '', '', 'Onegai My Melody', '', '', '', '', ''),
-- ('お前はまだグンマを知らない', '', '', '', 'Omae wa Mada Gunma o Shiranai', '', '', '', '', ''),
-- ('お見合い相手は教え子、強気な、問題児。', '', '', '', 'Omiai Aite wa Oshiego', '', '', '', '', ''),
-- ('終物語', '', '', '', 'Owarimonogatari', '', '', '', '', ''),
-- ('陰陽師・平安物語', '', '', '', 'Onmyouji: Heian Monogatari', '', '', '', '', ''),
-- ('かいけつゾロリ', '', '', '', 'Kaiketsu Zorori', '', '', '', '', ''),
-- ('かくりよの宿飯', '', '', '', 'Kakuriyo: Bed and Breakfast for Spirits', '', '', '', '', ''),
-- ('風が強く吹いている', '', '', '', 'Run with the Wind', '', '', '', '', ''),
-- ('風のスティグマ', '', '', '', 'Kaze no Stigma', '', '', '', '', ''),
-- ('刀語', '', '', '', 'Katanagatari', '', '', '', '', ''),
-- ('彼女がフラグおられたら', '', '', '', 'If Her Flag Breaks', '', '', '', '', ''),
-- ('彼女と彼女の猫', '', '', '', 'She and Her Cat', '', '', '', '', ''),
-- ('歌舞伎町シャーロック', '', '', '', 'Kabukichō Sherlock', '', '', '', '', ''),
-- ('神々の悪戯', '', '', '', 'Kamigami no Asobi', '', '', '', '', ''),
-- ('神さまのいない日曜日', '', '', '', 'Sunday Without God', '', '', '', '', ''),
-- ('神様のメモ帳', '', '', '', "Heaven's Memo Pad", '', '', '', '', ''),
-- ('神様はじめました', '', '', '', 'Kamisama Kiss', '', '', '', '', ''),
-- ('彼氏彼女の事情', '', '', '', 'Kare Kano', '', '', '', '', ''),
-- ('可愛ければ変態でも好きになってくれますか？', '', '', '', 'Hensuki', '', '', '', '', ''),
-- ('艦隊これくしょん', '', '', '', 'Kantai Collection', '', '', '', '', ''),
-- ('ガイコツ書店員 本田さん', '', '', '', 'Skull-face Bookseller Honda-san', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
-- ('', '', '', '', '', '', '', '', '', ''),
